/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProductIndexRouteImport } from './routes/_authenticated/product/index'
import { Route as AuthenticatedGalleryIndexRouteImport } from './routes/_authenticated/gallery/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCordlessIndexRouteImport } from './routes/_authenticated/cordless/index'
import { Route as AuthenticatedCategoryIndexRouteImport } from './routes/_authenticated/category/index'
import { Route as AuthenticatedCatalogueIndexRouteImport } from './routes/_authenticated/catalogue/index'
import { Route as AuthenticatedArticleIndexRouteImport } from './routes/_authenticated/article/index'
import { Route as AuthenticatedProductIdRouteImport } from './routes/_authenticated/product/$id'
import { Route as AuthenticatedCategoryIdRouteImport } from './routes/_authenticated/category/$id'
import { Route as AuthenticatedArticleCreateRouteImport } from './routes/_authenticated/article/create'
import { Route as AuthenticatedArticleIdRouteImport } from './routes/_authenticated/article/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductIndexRoute =
  AuthenticatedProductIndexRouteImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGalleryIndexRoute =
  AuthenticatedGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCordlessIndexRoute =
  AuthenticatedCordlessIndexRouteImport.update({
    id: '/cordless/',
    path: '/cordless/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoryIndexRoute =
  AuthenticatedCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogueIndexRoute =
  AuthenticatedCatalogueIndexRouteImport.update({
    id: '/catalogue/',
    path: '/catalogue/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticleIndexRoute =
  AuthenticatedArticleIndexRouteImport.update({
    id: '/article/',
    path: '/article/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductIdRoute = AuthenticatedProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoryIdRoute = AuthenticatedCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArticleCreateRoute =
  AuthenticatedArticleCreateRouteImport.update({
    id: '/article/create',
    path: '/article/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticleIdRoute = AuthenticatedArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/article/$id': typeof AuthenticatedArticleIdRoute
  '/article/create': typeof AuthenticatedArticleCreateRoute
  '/category/$id': typeof AuthenticatedCategoryIdRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
  '/article': typeof AuthenticatedArticleIndexRoute
  '/catalogue': typeof AuthenticatedCatalogueIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/cordless': typeof AuthenticatedCordlessIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/gallery': typeof AuthenticatedGalleryIndexRoute
  '/product': typeof AuthenticatedProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/article/$id': typeof AuthenticatedArticleIdRoute
  '/article/create': typeof AuthenticatedArticleCreateRoute
  '/category/$id': typeof AuthenticatedCategoryIdRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
  '/article': typeof AuthenticatedArticleIndexRoute
  '/catalogue': typeof AuthenticatedCatalogueIndexRoute
  '/category': typeof AuthenticatedCategoryIndexRoute
  '/cordless': typeof AuthenticatedCordlessIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/gallery': typeof AuthenticatedGalleryIndexRoute
  '/product': typeof AuthenticatedProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/article/$id': typeof AuthenticatedArticleIdRoute
  '/_authenticated/article/create': typeof AuthenticatedArticleCreateRoute
  '/_authenticated/category/$id': typeof AuthenticatedCategoryIdRoute
  '/_authenticated/product/$id': typeof AuthenticatedProductIdRoute
  '/_authenticated/article/': typeof AuthenticatedArticleIndexRoute
  '/_authenticated/catalogue/': typeof AuthenticatedCatalogueIndexRoute
  '/_authenticated/category/': typeof AuthenticatedCategoryIndexRoute
  '/_authenticated/cordless/': typeof AuthenticatedCordlessIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/gallery/': typeof AuthenticatedGalleryIndexRoute
  '/_authenticated/product/': typeof AuthenticatedProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/article/$id'
    | '/article/create'
    | '/category/$id'
    | '/product/$id'
    | '/article'
    | '/catalogue'
    | '/category'
    | '/cordless'
    | '/dashboard'
    | '/gallery'
    | '/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/article/$id'
    | '/article/create'
    | '/category/$id'
    | '/product/$id'
    | '/article'
    | '/catalogue'
    | '/category'
    | '/cordless'
    | '/dashboard'
    | '/gallery'
    | '/product'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/article/$id'
    | '/_authenticated/article/create'
    | '/_authenticated/category/$id'
    | '/_authenticated/product/$id'
    | '/_authenticated/article/'
    | '/_authenticated/catalogue/'
    | '/_authenticated/category/'
    | '/_authenticated/cordless/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/gallery/'
    | '/_authenticated/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/product/': {
      id: '/_authenticated/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthenticatedProductIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery/': {
      id: '/_authenticated/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cordless/': {
      id: '/_authenticated/cordless/'
      path: '/cordless'
      fullPath: '/cordless'
      preLoaderRoute: typeof AuthenticatedCordlessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category/': {
      id: '/_authenticated/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AuthenticatedCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue/': {
      id: '/_authenticated/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/': {
      id: '/_authenticated/article/'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof AuthenticatedArticleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/product/$id': {
      id: '/_authenticated/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AuthenticatedProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category/$id': {
      id: '/_authenticated/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof AuthenticatedCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/create': {
      id: '/_authenticated/article/create'
      path: '/article/create'
      fullPath: '/article/create'
      preLoaderRoute: typeof AuthenticatedArticleCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/$id': {
      id: '/_authenticated/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof AuthenticatedArticleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArticleIdRoute: typeof AuthenticatedArticleIdRoute
  AuthenticatedArticleCreateRoute: typeof AuthenticatedArticleCreateRoute
  AuthenticatedCategoryIdRoute: typeof AuthenticatedCategoryIdRoute
  AuthenticatedProductIdRoute: typeof AuthenticatedProductIdRoute
  AuthenticatedArticleIndexRoute: typeof AuthenticatedArticleIndexRoute
  AuthenticatedCatalogueIndexRoute: typeof AuthenticatedCatalogueIndexRoute
  AuthenticatedCategoryIndexRoute: typeof AuthenticatedCategoryIndexRoute
  AuthenticatedCordlessIndexRoute: typeof AuthenticatedCordlessIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedGalleryIndexRoute: typeof AuthenticatedGalleryIndexRoute
  AuthenticatedProductIndexRoute: typeof AuthenticatedProductIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArticleIdRoute: AuthenticatedArticleIdRoute,
  AuthenticatedArticleCreateRoute: AuthenticatedArticleCreateRoute,
  AuthenticatedCategoryIdRoute: AuthenticatedCategoryIdRoute,
  AuthenticatedProductIdRoute: AuthenticatedProductIdRoute,
  AuthenticatedArticleIndexRoute: AuthenticatedArticleIndexRoute,
  AuthenticatedCatalogueIndexRoute: AuthenticatedCatalogueIndexRoute,
  AuthenticatedCategoryIndexRoute: AuthenticatedCategoryIndexRoute,
  AuthenticatedCordlessIndexRoute: AuthenticatedCordlessIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedGalleryIndexRoute: AuthenticatedGalleryIndexRoute,
  AuthenticatedProductIndexRoute: AuthenticatedProductIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
